# -*- coding: utf-8 -*-
import sys

# Form implementation generated from reading ui file 'output.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QEventLoop, QTimer


class Ui_output(object):
    def setupUi(self, output):
        output.setObjectName("output")
        output.resize(800, 600)
        output.setMinimumSize(QtCore.QSize(800, 600))
        output.setMaximumSize(QtCore.QSize(800, 600))
        output.move(400,400)
        self.centralwidget = QtWidgets.QWidget(output)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.outputwindow = QtWidgets.QTextBrowser(self.centralwidget)
        self.outputwindow.setObjectName("outputwindow")
        self.verticalLayout.addWidget(self.outputwindow)
        # self.kline = QtWidgets.QPushButton(self.centralwidget)
        # self.kline.setObjectName("kline")
        # self.verticalLayout.addWidget(self.kline)
        output.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(output)
        self.statusbar.setObjectName("statusbar")
        output.setStatusBar(self.statusbar)

        sys.stdout = EmittingStr(textWritten=self.outputWritten)
        sys.stderr = EmittingStr(textWritten=self.outputWritten)

        self.retranslateUi(output)
        QtCore.QMetaObject.connectSlotsByName(output)

    def retranslateUi(self, output):
        _translate = QtCore.QCoreApplication.translate
        output.setWindowTitle(_translate("output", "output"))
        # self.kline.setText(_translate("output", "k线图"))

    def outputWritten(self, text):
        cursor = self.outputwindow.textCursor()
        cursor.movePosition(QtGui.QTextCursor.End)
        cursor.insertText(text)
        self.outputwindow.setTextCursor(cursor)
        self.outputwindow.ensureCursorVisible()


class EmittingStr(QtCore.QObject):
    textWritten = QtCore.pyqtSignal(str) #定义一个发送str的信号
    def write(self, text):
      self.textWritten.emit(str(text))
      loop = QEventLoop()
      QTimer.singleShot(10, loop.quit)
      loop.exec_()