# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recommend.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_recommend(object):
    def setupUi(self, recommend):
        recommend.setObjectName("recommend")
        recommend.resize(800, 600)
        recommend.setMinimumSize(QtCore.QSize(800, 600))
        recommend.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(recommend)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 20, 91, 23))
        self.pushButton.setObjectName("pushButton")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(170, 20, 621, 551))
        self.listWidget.setObjectName("listWidget")
        recommend.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(recommend)
        self.statusbar.setObjectName("statusbar")
        recommend.setStatusBar(self.statusbar)

        self.retranslateUi(recommend)
        QtCore.QMetaObject.connectSlotsByName(recommend)

    def retranslateUi(self, recommend):
        _translate = QtCore.QCoreApplication.translate
        recommend.setWindowTitle(_translate("recommend", "recommend"))
        self.pushButton.setText(_translate("recommend", "查看推荐股票"))
