
import sys

from PyQt5.QtCore import QEventLoop, QTimer

# Form implementation generated from reading ui file 'testUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import gol
from backtest2 import date_backtest2

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow

class EmittingStr(QtCore.QObject):
    textWritten = QtCore.pyqtSignal(str) #定义一个发送str的信号
    def write(self, text):
      self.textWritten.emit(str(text))
      loop = QEventLoop()
      QTimer.singleShot(10, loop.quit)
      loop.exec_()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1231, 906)
        MainWindow.setMinimumSize(QtCore.QSize(1231, 906))
        MainWindow.setMaximumSize(QtCore.QSize(1231, 906))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.code = QtWidgets.QTextEdit(self.centralwidget)
        self.code.setGeometry(QtCore.QRect(40, 40, 141, 31))
        self.code.setObjectName("code")
        self.start = QtWidgets.QTextEdit(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(40, 110, 141, 31))
        self.start.setObjectName("start")
        self.end = QtWidgets.QTextEdit(self.centralwidget)
        self.end.setGeometry(QtCore.QRect(40, 180, 141, 31))
        self.end.setObjectName("end")
        self.condition_rsi = QtWidgets.QTextEdit(self.centralwidget)
        self.condition_rsi.setGeometry(QtCore.QRect(40, 250, 141, 31))
        self.condition_rsi.setObjectName("condition_rsi")
        self.special_buy_rsi = QtWidgets.QTextEdit(self.centralwidget)
        self.special_buy_rsi.setGeometry(QtCore.QRect(40, 320, 141, 31))
        self.special_buy_rsi.setObjectName("special_buy_rsi")
        self.special_sell_rsi = QtWidgets.QTextEdit(self.centralwidget)
        self.special_sell_rsi.setGeometry(QtCore.QRect(40, 400, 141, 31))
        self.special_sell_rsi.setObjectName("special_sell_rsi")
        self.principal = QtWidgets.QTextEdit(self.centralwidget)
        self.principal.setGeometry(QtCore.QRect(40, 480, 141, 31))
        self.principal.setObjectName("principal")
        self.special_sell_rsi_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.special_sell_rsi_3.setGeometry(QtCore.QRect(40, 550, 141, 31))
        self.special_sell_rsi_3.setObjectName("special_sell_rsi_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(70, 630, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(300, 10, 891, 861))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 20, 54, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 90, 54, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 150, 54, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 220, 131, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 290, 131, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 370, 131, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(190, 50, 131, 20))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(190, 120, 131, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(190, 190, 131, 20))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(190, 260, 131, 20))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(190, 330, 131, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(190, 410, 61, 21))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(80, 450, 61, 20))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(90, 530, 41, 20))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(190, 480, 131, 21))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(190, 560, 81, 21))
        self.label_16.setObjectName("label_16")
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        self.clear.setGeometry(QtCore.QRect(70, 710, 75, 23))
        self.clear.setObjectName("clear")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        # 允许tab切换
        self.code.setTabChangesFocus(True)
        self.start.setTabChangesFocus(True)
        self.end.setTabChangesFocus(True)
        self.condition_rsi.setTabChangesFocus(True)
        self.special_buy_rsi.setTabChangesFocus(True)
        self.special_sell_rsi.setTabChangesFocus(True)
        self.principal.setTabChangesFocus(True)
        self.special_sell_rsi_3.setTabChangesFocus(True)
        # 设置默认值
        self.code.setPlainText('600073.SH')
        self.start.setPlainText('20220325')
        self.end.setPlainText('20220614')
        self.condition_rsi.setPlainText('0.1')
        self.special_buy_rsi.setPlainText('0.2')
        self.special_sell_rsi.setPlainText('0.1')
        self.principal.setPlainText('9999999')
        self.special_sell_rsi_3.setPlainText('0.3')

        sys.stdout = EmittingStr(textWritten=self.outputWritten)
        sys.stderr = EmittingStr(textWritten=self.outputWritten)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(self.run)
        self.clear.clicked.connect(self.special_sell_rsi_3.clear)
        self.clear.clicked.connect(self.principal.clear)
        self.clear.clicked.connect(self.special_sell_rsi.clear)
        self.clear.clicked.connect(self.special_buy_rsi.clear)
        self.clear.clicked.connect(self.condition_rsi.clear)
        self.clear.clicked.connect(self.end.clear)
        self.clear.clicked.connect(self.start.clear)
        self.clear.clicked.connect(self.code.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "股票代码"))
        self.label_2.setText(_translate("MainWindow", "开始时间"))
        self.label_3.setText(_translate("MainWindow", "结束时间"))
        self.label_4.setText(_translate("MainWindow", "买卖条件1的RSI变化率"))
        self.label_5.setText(_translate("MainWindow", "特殊条件买入RSI变化率"))
        self.label_6.setText(_translate("MainWindow", "特殊条件卖出RSI变化率"))
        self.label_7.setText(_translate("MainWindow", "如：600073.SH"))
        self.label_8.setText(_translate("MainWindow", "如：20220325"))
        self.label_9.setText(_translate("MainWindow", "如：20220614"))
        self.label_10.setText(_translate("MainWindow", "如：0.1"))
        self.label_11.setText(_translate("MainWindow", "如：0.2"))
        self.label_12.setText(_translate("MainWindow", "如：0.1"))
        self.pushButton.setText(_translate("MainWindow", "回测"))
        self.label_13.setText(_translate("MainWindow", "初始资金"))
        self.label_14.setText(_translate("MainWindow", "止损率"))
        self.label_15.setText(_translate("MainWindow", "如：999999"))
        self.label_16.setText(_translate("MainWindow", "如：0.3"))
        self.clear.setText(_translate("MainWindow", "清除"))

    def outputWritten(self, text):
        cursor = self.textBrowser.textCursor()
        cursor.movePosition(QtGui.QTextCursor.End)
        cursor.insertText(text)
        self.textBrowser.setTextCursor(cursor)
        self.textBrowser.ensureCursorVisible()

    def run(self):
        code = self.code.toPlainText()
        start = self.start.toPlainText()
        end = self.end.toPlainText()
        condition_rsi = float(self.condition_rsi.toPlainText())
        special_buy_rsi = float(self.special_buy_rsi.toPlainText())
        special_sell_rsi = float(self.special_sell_rsi.toPlainText())
        principal = float(self.principal.toPlainText())
        # stoploss忘记改了
        stoploss = float(self.special_sell_rsi_3.toPlainText())
        gol.set_value('special_buy_rsi',special_buy_rsi)
        gol.set_value('special_sell_rsi',special_sell_rsi)
        date_backtest2(start,end,code,principal,condition_rsi,stoploss,False,True)



if __name__ == "__main__":
    App = QApplication(sys.argv)  # 创建QApplication对象，作为GUI主程序入口
    aw = Ui_MainWindow()  # 创建主窗体对象，实例化Ui_MainWindow
    w = QMainWindow()  # 实例化QMainWindow类
    aw.setupUi(w)  # 主窗体对象调用setupUi方法，对QMainWindow对象进行设置
    w.show()  # 显示主窗体
    # App.exit()
    sys.exit(App.exec_())  # 循环中等待退出程序